name: ci

on:
  push:
    branches:
    - main
  pull_request:
    types: [opened, reopened, synchronize]

permissions: {}  # deny all; jobs declare only what they need

# This job installs dependencies, runs tests, and checks formatting
jobs:
  run-ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        python-version:
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"

    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4

    - name: Install uv
      uses: astral-sh/setup-uv@6dfebec6ddbcd197e02256fbdf54deb334fb7f06  # v2
      with:
        version: "0.4.10"
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: run tests
      run: |
        uv run pytest tests/

    - name: check-format
      run: |
        uv run ruff check
