name: ci

on:
  push:
    branches:
    - main
  pull_request:
    types: [opened, reopened]

# This job installs dependencies, runs tests, and checks formatting
jobs:
  run-ci:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    strategy:
      matrix:
        python-version:
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        # Install a specific version of uv.
        version: "0.4.10"
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: run tests
      run: |
        uv run pytest tests/

    - name: check-format
      run: |
        uv run ruff check