name: Publish Python 🐍 distribution 📦 to PyPI and TestPyPI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions: {}  # deny all; jobs declare only what they need

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment: pypi-production
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4

    - name: Install uv
      uses: astral-sh/setup-uv@6dfebec6ddbcd197e02256fbdf54deb334fb7f06  # v2
      with:
        version: "0.4.10"
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: "Set up Python"
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5
      with:
        python-version-file: ".python-version"

    - name: Install the project
      run: uv sync --all-extras --dev

    # run tests and check formatting
    - name: run tests
      run: |
        uv run pytest tests/

    - name: check-format
      run: |
        uv run ruff check

    # build and publish
    - name: build project
      run: uv build

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PY_PI_API_TOKEN }}
      run: uvx twine upload dist/* --non-interactive
